name: Deploy Project

on:
  push:
    branches: main

jobs:
  gh-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.85.0'
      - name: Install and Build
        run: |
          git config --global user.email "kimgs0725@gmail.com"
          git config --global user.name "wondsn"
          # npm ci
          yarn install
          yarn run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          user_email: 'kimgs0725@gmail.com'
          user_name: 'wondsn'
          github_token: ${{ secrets.ACCESS_TOKEN }}
          # branch: master # The branch the action should deploy to.
          publish_branch: gh-pages
          publish_dir: build # The folder the action should deploy.
